name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        docker build -t aidanadevops2023/project-eks-deploy:latest .
        docker push aidanadevops2023/project-eks-deploy:latest

    # Step 4: Configure AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 5: Update kubeconfig
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

    # Step 6: Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f deploymen.yaml
        kubectl apply -f service.yml

